# Generated by Django 4.2.3 on 2023-07-12 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceries_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registereduser',
            name='profile_pic',
            field=models.ImageField(default='default.jpg', upload_to='profile_pic'),
        ),
    ]
