# Generated by Django 3.1.4 on 2020-12-14 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceries_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registereduser',
            name='profilePic',
            field=models.ImageField(default='default.jpeg', upload_to='profile_pics'),
        ),
    ]
