# Generated by Django 4.2.3 on 2023-07-04 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IIS_APP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateTestsuite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobname', models.CharField(max_length=100)),
                ('emailid', models.CharField(max_length=100)),
                ('Testsuite', models.CharField(max_length=100)),
                ('envirionment', models.CharField(max_length=100)),
            ],
        ),
    ]
