# Generated by Django 4.2.3 on 2023-08-09 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IIS_APP', '0002_createtestsuite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createtestsuite',
            name='Testsuite',
            field=models.CharField(choices=[('s5reg', 's5reg'), ('paralletestsuite1', 'paralletestsuite1'), ('paralletestsuite2', 'paralletestsuite2'), ('paralletestsuite3', 'paralletestsuite3'), ('paralletestsuite4', 'paralletestsuite4'), ('paralletestsuite5', 'paralletestsuite5'), ('Fullregtestsuite', 'Fullregtestsuite')], default='Fullregtestsuite', max_length=100),
        ),
        migrations.AlterField(
            model_name='createtestsuite',
            name='envirionment',
            field=models.CharField(choices=[('FT1', 'FT1'), ('FT2', 'FT2'), ('FT3', 'FT3'), ('SIT', 'SIT'), ('UAT', 'UAT')], default='FT1', max_length=100),
        ),
    ]
